### PR TITLE
[Docs] update dependency version req, dockerfile and change logs for 0.2.1

### PR DESCRIPTION
**Pull request by gaotongxiao**
Docs & dockerfile update for 0.2.1

### CODE REVIEW

**Comment by innerlee** [comment]
Is there a related issue in pytorch's repo?

**Comment by gaotongxiao** [comment]
https://github.com/pytorch/pytorch/issues/33870

**Comment by innerlee** [comment]
Reading the pytorch thread, it seems that it is caused by op on mixing devices. At #271, there is a cpu and a cuda

image

It seems that this could be avoided if we write code in fcenet more careful, correct?

**Comment by gaotongxiao** [comment]
Yes. It's the quickest way to "fix" this issue though.

**Comment by innerlee** [comment]
I'm not a fan of upgrading dependencies. It means that previously working code will refuse to run after upgrading. This will hurt old users.

Fixing the error from the code side would be great.

**Comment by gaotongxiao** [comment]
I'll create a PR for init_cfg support soon which would also upgrade dependencies. By that time the results of the retrianing process can better prove that this upgrade is safe. We can hold the PR till then.

**Comment by gaotongxiao** [comment]
To be merged together with the release of 0.2.1

**Comment by gaotongxiao** [comment]
Date & version are subject to change. Will review 2 community PRs then and decide if they can be merged into this release.

**Review by cuhk-hbsun — APPROVED** [review]

**Pull request merged**
