### PR TITLE
[Bugs] fix crop without padding and recog metainfo delete unuse info

### PR DESCRIPTION
**Pull request by Harold-lkk**
Delete category in rec json
```python
    "metainfo": {
        "dataset_type": "TextRecogDataset",
        "task_name": "textrecog",
        "category": [
            {
                "id": 0,
                "name": "text"
            }
        ]
    }
```

`TextRecogCropConverter` defaults not to padding in `crop image`

### CODE REVIEW

**Comment by Harold-lkk** [comment]
merge before #1506

**Comment by xinke-wang** [comment]
A question here, in 0.x version, the pad ratio was set as `0.4` and `0.2` by default. I am not sure if this matters to the test performance. Though personally, I think it should be set to `0` as this PR, maybe someone should test the model to see if it works as expected.

https://github.com/open-mmlab/mmocr/blob/26bc4713d4a451ed510a67be0a4fdd9903fd9011/mmocr/datasets/pipelines/crop.py#L87-L97

**Comment by Harold-lkk** [comment]
> A question here, in 0.x version, the pad ratio was set as `0.4` and `0.2` by default. I am not sure if this matters to the test performance. Though personally, I think it should be set to `0` as this PR, maybe someone should test the model to see if it works as expected.
> 
> https://github.com/open-mmlab/mmocr/blob/26bc4713d4a451ed510a67be0a4fdd9903fd9011/mmocr/datasets/pipelines/crop.py#L87-L97

I have tested. Difference image shape will affect the performance.
In the 0.x version, the `crop image` is only used for ocr.py, because of bad performance of text detection

**Comment by xinke-wang** [comment]
> > A question here, in 0.x version, the pad ratio was set as `0.4` and `0.2` by default. I am not sure if this matters to the test performance. Though personally, I think it should be set to `0` as this PR, maybe someone should test the model to see if it works as expected.
> > https://github.com/open-mmlab/mmocr/blob/26bc4713d4a451ed510a67be0a4fdd9903fd9011/mmocr/datasets/pipelines/crop.py#L87-L97
> 
> I have tested. Difference image shape will affect the performance. In the 0.x version, the `crop image` is only used for ocr.py, because of bad performance of text detection

Ok. It is noteworthy that some converters such as totaltext converter also used the `crop_image` and the default setting. I am not sure if it affects totaltext's performance.

https://github.com/open-mmlab/mmocr/blob/26bc4713d4a451ed510a67be0a4fdd9903fd9011/tools/data/textrecog/totaltext_converter.py#L302

**Review by gaotongxiao — APPROVED** [review]

**Comment by Harold-lkk** [comment]
> crop_img

Maybe it's a bug. I check other data_converter, and they are all `crop_img(image, anno['bbox'], 0, 0)`

**Review by xinke-wang — APPROVED** [review]

**Review by gaotongxiao — APPROVED** [review]

**Pull request merged**
