### PR TITLE
Start test scripts!

### PR DESCRIPTION
**Pull request by innerlee**
The first example for https://github.com/open-mmlab/mmocr/issues/313

### CODE REVIEW

**Comment by innerlee** [comment]
TODO:

* cache checkpoints
* make more scripts support cpu
* fix tests

**Comment by innerlee** [comment]
Currently CI fails because of the inconsistency behavior of cpu/gpu in mmcv due to this pr https://github.com/open-mmlab/mmcv/pull/497/files.

**Comment by yauauau** [comment]
Ho

**Comment by yauauau** [comment]
build / build_cuda (1.8.0+cu101, 3.8, 1.8.0, 0.9.0+cu101) (pull_request) Cancelled after 10m — build_cuda (1.8.0+cu101, 3.8, 1.8.0, 0.9.0+cu101)

**Pull request closed without merging**
