### PR TITLE
add web demo link

### PR DESCRIPTION
**Pull request by AK391**
added link for web demo on Hugging Face Spaces using Gradio by https://huggingface.co/tomofi

### CODE REVIEW

**Comment by gaotongxiao** [comment]
Hi, thanks for your PR and we really appreciate it! It is a very interesting demo and I believe it's pretty helpful for many users. However, I'm afraid it could not be merged into our repository for now. Usually, we welcome PRs whose contents are fully accessible and verifiable at any time. But this PR links users to an external private implementation to which we do not gain full access. As such, we are not able to officially guarantee the correctness and transparency of this "black box" to our community. Therefore, I'm closing this PR and I hope you can understand our choice. Thank you again, and looking forward to your next contribution!

**Comment by AK391** [comment]
@gaotongxiao thanks for the feedback all demos on Huggingface spaces are open source, you can see the demo code here https://huggingface.co/spaces/tomofi/MMOCR/tree/main, similar to github

more about spaces: https://huggingface.co/spaces/launch

**Comment by AK391** [comment]
also this is the code for the app: https://huggingface.co/spaces/tomofi/MMOCR/blob/main/app.py

**Comment by AK391** [comment]
also if you prefer you can setup a Gradio demo in your own organization on Hugging Face

Example from other organizations:
Keras: https://huggingface.co/keras-io
Microsoft: https://huggingface.co/microsoft
Facebook: https://huggingface.co/facebook

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/akhaliq/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

**Comment by gaotongxiao** [comment]
Sounds great! We will delve into this option, but it can take some time before we conclude. Anyway, thanks for all the information!

**Pull request closed without merging**
