### PR TITLE
[Fix] Support loading space character from dict file

### PR DESCRIPTION
**Pull request by gaotongxiao**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

`BaseConvertor` used to skip any whitespace when loading a dictionary from a file. For example, one passes a legal dictionary file to `label_convertor` where the third line is a space character:

```
a
b
 
d
```

And they would expect the label convertor to create the dictionary as `['a', 'b', ' ', 'd']` but get `['a', 'b', 'd']` instead. This PR improves the parser by stripping only line-breaking characters (`\r` and `\n`) from each line and retaining the space character. 

## Modifications

1. Improve on the parsing part of `BaseConvertor.__init__()`
3. Add more unit tests for `BaseConvertor`

## BC-breaking (Optional)

A dictionary containing duplicated characters will be regarded as an invalid input and break the assertion of the label convertor. It was permitted implicitly before, but usually we don't want `label_convertor` to generate ambiguous results.

### CODE REVIEW

**Comment by xinke-wang** [comment]
I have a question is that the 'DICT36' and 'DICT90' do not contain space. So, if the users would like to train a dataset that contains space, they have to modify the DICT manually. Do we need to provide an optional parameter (or a dict containing space) to allow users to enable space recognition in a faster way?

**Comment by gaotongxiao** [comment]
@xinke-wang Space character is not as special as `<UNK>`, `<PAD>`, `<BOS/EOS>`, so principally we should not design an optional argument for space recognition. Providing `DICT37` and `DICT91` and informing users of their availability in both the tutorial (https://github.com/open-mmlab/mmocr/pull/850) and the release log sound more appealing to me.

**Comment by xinke-wang** [comment]
> @xinke-wang Space character is not as special as `<UNK>`, `<PAD>`, `<BOS/EOS>`, so principally we should not design an optional argument for space recognition. Providing `DICT37` and `DICT91` and informing users of their availability in both the tutorial (#850) and the release log sound more appealing to me.

Ok, I will add instructions to #850.

**Review by xinke-wang — APPROVED** [review]

**Comment by xinke-wang** [comment]
Since we now support `DICT37` and `DICT91`, the docstring of BaseConvertor should be updated.

`dict_type (str): Type of dict, should be either 'DICT36' or 'DICT90'`

**Review by xinke-wang — APPROVED** [review]

**Pull request merged**
