### PR TITLE
[Enhancement] Remove unnecessary custom_import from train.py

### PR DESCRIPTION
**Pull request by gaotongxiao**
Removing it as MMCV can handle this field.

### CODE REVIEW

**Comment by Harold-lkk** [comment]
so where to import custom import

**Comment by gaotongxiao** [comment]
@zhouzaida

**Review by zhouzaida — APPROVED** [review]

**Comment by Harold-lkk** [comment]
Do we need to limit MMCV version?

**Comment by gaotongxiao** [comment]
MMCV started to support this from 1.1.6.

**Review by cuhk-hbsun — APPROVED** [review]

**Comment by Harold-lkk** [comment]
Reference to https://github.com/open-mmlab/mmcv/pull/606

**Pull request merged**
