### PR TITLE
[Docs] Add Chinese Guidance on How to Add New Datasets to Dataset Preparer

### PR DESCRIPTION
**Pull request by xinke-wang**
Add Guidance on How to Add New Datasets to Dataset Preparer (Chinese Version Only), using ICDAR 2013 dataset as an example. Also, this PR adds the IC13 dataset to the dataset preparer.

### CODE REVIEW

**Comment by gaotongxiao** [comment]
Tested CRNN on IC13 test split generated by the dataset preparer, got 82.65 instead of 87.39 (https://mmocr.readthedocs.io/en/dev-1.x/textrecog_models.html#id5). The same issue has also been found on IC15. I'll investigate such a difference.

**Comment by gaotongxiao** [comment]
Dataset preparer now generates 1095 test images without post-filtering, which is usually required. (https://arxiv.org/pdf/1904.01906.pdf)

image

**Comment by gaotongxiao** [comment]
It might be easy to develop a post-filtering script for IC13, but IC15 is filtered manually and [may not be generated](https://mmocr.readthedocs.io/en/dev-1.x/user_guides/data_prepare/recog.html#icdar-2015).

**Comment by xinke-wang** [comment]
We may comment the original URL, and add the specified version of annotation just like the old [converter](https://mmocr.readthedocs.io/en/latest/datasets/recog.html#icdar-2015).

**Comment by xinke-wang** [comment]
> It might be easy to develop a post-filtering script for IC13, but IC15 is filtered manually and [may not be generated](https://mmocr.readthedocs.io/en/dev-1.x/user_guides/data_prepare/recog.html#icdar-2015). Shall we allow users to download existing annotations for these special cases?

I can raise a new PR to fix this issue

**Review by gaotongxiao — APPROVED** [review]

**Comment by gaotongxiao** [comment]
@xinke-wang Yes, we need to download annotations by default for IC13&15 textrecog datasets. I can upload the filtered annotations for IC13 and IC15 if needed.

**Comment by xinke-wang** [comment]
> @xinke-wang Yes, we need to download annotations by default for IC13&15 textrecog datasets. I can upload the filtered annotations for IC13 and IC15 if needed. I think I'll not merge this PR till your get the new PR ready.

I've added the 1015 version for IC13. However, after checking the link provided by the doc https://mmocr.readthedocs.io/en/latest/datasets/recog.html#icdar-2015, it seems the 2077 IC15 was used? Can you check if MMOCR models were tested on IC15 2077 or IC15 1811?

**Comment by Harold-lkk** [comment]
Can split pr into several parts for not blocking other pr:
* icdar13 prepare
* guide docs
* bugfix: icdarparser
* metafile fix: WildReceipt

**Comment by Harold-lkk** [comment]
> > @xinke-wang Yes, we need to download annotations by default for IC13&15 textrecog datasets. I can upload the filtered annotations for IC13 and IC15 if needed. I think I'll not merge this PR till your get the new PR ready.
> 
> I've added the 1015 version for IC13. However, after checking the link provided by the doc https://mmocr.readthedocs.io/en/latest/datasets/recog.html#icdar-2015, it seems the 2077 IC15 was used? Can you check if MMOCR models were tested on IC15 2077 or IC15 1811?

2077 for recogintion test

**Comment by xinke-wang** [comment]
> > > @xinke-wang Yes, we need to download annotations by default for IC13&15 textrecog datasets. I can upload the filtered annotations for IC13 and IC15 if needed. I think I'll not merge this PR till your get the new PR ready.
> > 
> > 
> > I've added the 1015 version for IC13. However, after checking the link provided by the doc https://mmocr.readthedocs.io/en/latest/datasets/recog.html#icdar-2015, it seems the 2077 IC15 was used? Can you check if MMOCR models were tested on IC15 2077 or IC15 1811?
> 
> 2077 for recogintion test

Ok, so we do not need to fix the IC15 preparer.

**Comment by xinke-wang** [comment]
> Can split pr into several parts for not blocking other pr:
> 
>     * icdar13 prepare
> 
>     * guide docs
> 
>     * bugfix: icdarparser
> 
>     * metafile fix: WildReceipt

Split to bug fix #1529 & metafile fix #1528 

Guidance is based on the IC13 preparer so I kept it in this PR.

**Pull request merged**
