### PR TITLE
add print_config.py to the tools

### PR DESCRIPTION
**Pull request by IncludeMathH**
#1545 
## Motivation

In previous versions of mmocr, as well as in projects such as mmdetection, there was a program (tools/misc/print_config.py) that could print out the complete configuration file directly. There is one reference in [MMDetection](https://github.com/open-mmlab/mmdetection/blob/3.x/tools/misc/print_config.py) which can almost be directly applied to MMOCR, so I just add it back.

## Modification

Add print_config.py back to tools/anaylsis_tools.

## Use cases (Optional)

It is a useful tool that can print out the complete configuration file directly. 

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmocr/blob/main/.github/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmocr/blob/main/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Review by gaotongxiao — COMMENTED** [review]
image
Thanks for your contribution! The file didn't pass our lint test due to the lack of the newline at the end of the file. Could you do a quick fix on it?

**Comment by IncludeMathH** [comment]
> image Thanks for your contribution! The file didn't pass our lint test due to the lack of the newline at the end of the file. Could you do a quick fix on it?

OK, I add a newline and install `pre-commit` this time, please check it again. Thank you for guiding me to participate in this project, this is my first time doing it!~
image

**Review by gaotongxiao — APPROVED** [review]
LGTM

**Comment by gaotongxiao** [comment]
@IncludeMathH Sure. Looking forward to seeing more of your work!

**Comment by OpenMMLab-Miao** [comment]
Dear IncludeMathH ,
First of all, we want to express our gratitude for your significant PR in the MMOCR project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.
If you are Chinese or have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. We look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG
Thank you again for your contribution❤
Best regards！ @IncludeMathH

**Pull request merged**
