### PR TITLE
[Feature] Add DeText Converter

### PR DESCRIPTION
**Pull request by xinke-wang**
## Motivation

Add data converter for [DeText](https://rrc.cvc.uab.es/?ch=9) dataset

## Modification

add tools for loading and converting labels from JSON annotations

```
tools/data/textdet/naf_converter.py
tools/data/textrecog/naf_converter.py
```

~~**Doc has not been fully updated yet, will be updated later.**~~
**Docs have been updated**

## Use cases (Optional)

Step1: Download ch9_training_images.zip, ch9_training_localization_transcription_gt.zip, ch9_validation_images.zip, and ch9_validation_localization_transcription_gt.zip from Task 3: End to End on the [homepage](https://rrc.cvc.uab.es/?ch=9).

```
mkdir detext && cd detext
mkdir imgs && mkdir annotations && mkdir imgs/training && mkdir imgs/val && mkdir annotations/training && mkdir annotations/val

% Extract images and annotations
unzip -q ch9_training_images.zip -d imgs/training && unzip -q ch9_training_localization_transcription_gt.zip -d annotations/training && unzip -q ch9_validation_images.zip -d imgs/val && unzip -q ch9_validation_localization_transcription_gt.zip -d annotations/val

% Remove zips
rm ch9_training_images.zip && rm ch9_training_localization_transcription_gt.zip && rm ch9_validation_images.zip && rm ch9_validation_localization_transcription_gt.zip
```

Screenshot from 2022-03-09 11-45-38

```bash
% det
python tools/data/textdet/detext_converter.py PATH/TO/detext --nproc 4

% recog
python tools/data/textrecog/detext_converter.py PATH/TO/detext --nproc 4
```

### CODE REVIEW

**Review by gaotongxiao — COMMENTED** [review]
TODO: Doc for recog

**Review by gaotongxiao — COMMENTED** [review]
Don't forget to mention the `--preserve-vertcial` option in the doc and the folder where ignored images will be saved

**Comment by xinke-wang** [comment]
> Don't forget to mention the `--preserve-vertcial` option in the doc and the folder where ignored images will be saved

Done; I will check other PRs if the same issues exist.

**Review by Mountchicken — APPROVED** [review]
Tested on sproject, everything works fine

**Review by gaotongxiao — APPROVED** [review]

**Pull request merged**
