### PR TITLE
[Fix] fix wrong import path

### PR DESCRIPTION
**Pull request by gaotongxiao**
#303

### CODE REVIEW

**Comment by innerlee** [comment]
Please add a test for running the script. See https://github.com/open-mmlab/mmcv/pull/1007 for how to do it

**Comment by gaotongxiao** [comment]
> Please add a test for running the script. See [open-mmlab/mmcv#1007](https://github.com/open-mmlab/mmcv/pull/1007) for how to do it

Would it be too slow or even impossible to finish the tests since most demo scripts involve model inference?

**Comment by innerlee** [comment]
Simply try it and fix it if run out of quota

**Comment by gaotongxiao** [comment]
> Simply try it and fix it if run out of quota

This script is GPU-only, so I tested it locally and LGTM. We may consider adding tests for other demo scripts in the future.

**Comment by innerlee** [comment]
> GPU-only

why

**Comment by gaotongxiao** [comment]
> > GPU-only
> 
> why

An op (`SyncBatchNorm`) of its default detection model, PSENet, has to be on GPU

**Review by cuhk-hbsun — APPROVED** [review]

**Pull request merged**
